---
# ====== Application: ESG_WEB ================================
identification: 
  name: ESG_WEB
  alias: ESG_WEB
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: No Authentication # 8657144791034776

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  http-response-headers: "Content-Security-Policy: default-src 'self'; connect-src 'self' https://ai.sustainacore.org; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'self'"

database-session: 
  parsing-schema: WKSP_ESGAPEX

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: SustainaCore

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN10020:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN10020

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation Menu # 8352304958992575

navigation-bar: 
  implementation: List
  list: Navigation Bar # 8641524613993519
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

css: 
  file-urls: 
  - 'https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 45527295114098

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Test

component-settings: 
- # ====== Component Setting: NATIVE_BOSS ======================
  id: 2994423319616106
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 41148916984018

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 8347445237992554
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 701167894

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 8347730521992557
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 701167920

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 8348003217992558
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 701167922

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 8348349608992559
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 701167922

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 8348612747992560
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 701167922

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 8348926447992561
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 701167927

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 8349236644992562
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 701167940

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 8349536053992563
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 701167950

- # ====== Component Setting: NATIVE_IR ========================
  id: 8349855945992564
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 701167956

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 8350114326992565
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 701167962

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 8350465197992566
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 701167962

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 8350729866992567
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 701167962

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 8350920623992568
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 701167962

application-settings: 
- # ====== Application Setting: CHAT_API_URL ===================
  id: 39909169014666695
  identification: 
    name: CHAT_API_URL

  value: 
    value: 'http://143.47.244.255:8080'
    required: false

  advanced: 
    on-upgrade-keep-value: false

  subscription: 
    version-number: 45071970096102

