SET DEFINE ON
DEFINE MIGRATION_VERSION='&1'
DEFINE MIGRATION_FILE='&2'
PROMPT Applying &&MIGRATION_VERSION from &&MIGRATION_FILE
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
@@&&MIGRATION_FILE
SET DEFINE ON
INSERT INTO schema_version(version) VALUES ('&&MIGRATION_VERSION');
COMMIT;
UNDEFINE MIGRATION_VERSION
UNDEFINE MIGRATION_FILE
EXIT;
