ALTER TABLE news_items ADD (body_html CLOB);

CREATE TABLE news_assets (
    asset_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id NUMBER,
    file_name VARCHAR2(512),
    mime_type VARCHAR2(128),
    file_blob BLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX ix_news_assets_news_id ON news_assets (news_id);

ALTER TABLE news_assets
    ADD CONSTRAINT fk_news_assets_news
    FOREIGN KEY (news_id)
    REFERENCES news_items (id)
    ON DELETE CASCADE;

CREATE OR REPLACE VIEW v_news_all (
    item_table,
    item_id,
    dt_pub,
    ticker,
    title,
    url,
    source_name,
    body,
    pillar_tags,
    full_text
) AS
SELECT
    'NEWS_ITEMS' AS item_table,
    ni.id AS item_id,
    CAST(ni.dt_pub AS timestamp) AS dt_pub,
    ni.ticker,
    ni.title,
    ni.url,
    ni.source AS source_name,
    ni.summary AS body,
    ni.pillar_tags,
    ni.body_html AS full_text
FROM news_items ni
UNION ALL
SELECT
    'ESG_NEWS' AS item_table,
    en.id AS item_id,
    CAST(en.date_published AS timestamp) AS dt_pub,
    NULL AS ticker,
    en.title,
    en.url,
    en.source AS source_name,
    SUBSTR(en.text, 1, 4000) AS body,
    NULL AS pillar_tags,
    en.text AS full_text
FROM esg_news en;

CREATE OR REPLACE VIEW v_news_enriched (
    item_table,
    item_id,
    dt_pub,
    ticker,
    title,
    url,
    source_name,
    body,
    pillar_tags,
    full_text,
    categories,
    tags,
    tickers
) AS
WITH base AS (
    SELECT a.* FROM v_news_all a
)
SELECT
    b.item_table,
    b.item_id,
    b.dt_pub,
    b.ticker,
    b.title,
    b.url,
    b.source_name,
    b.body,
    b.pillar_tags,
    b.full_text,
    (SELECT LISTAGG(c.name, ', ') WITHIN GROUP (ORDER BY c.name)
        FROM news_item_categories nic
        JOIN news_categories c ON c.category_id = nic.category_id
        WHERE nic.item_table=b.item_table AND nic.item_id=b.item_id) AS categories,
    (SELECT LISTAGG(t.name, ', ') WITHIN GROUP (ORDER BY t.name)
        FROM news_item_tags nit
        JOIN news_tags t ON t.tag_id = nit.tag_id
        WHERE nit.item_table=b.item_table AND nit.item_id=b.item_id) AS tags,
    (SELECT LISTAGG(nt.ticker, ', ') WITHIN GROUP (ORDER BY nt.ticker)
        FROM news_item_tickers nt
        WHERE nt.item_table=b.item_table AND nt.item_id=b.item_id) AS tickers
FROM base b;

CREATE OR REPLACE VIEW v_news_recent (
    item_table,
    item_id,
    dt_pub,
    ticker,
    title,
    url,
    source_name,
    body,
    pillar_tags,
    full_text,
    categories,
    tags,
    tickers
) AS
SELECT item_table, item_id, dt_pub, ticker, title, url, source_name, body, pillar_tags, full_text, categories, tags, tickers
FROM v_news_enriched
ORDER BY dt_pub DESC;

CREATE OR REPLACE VIEW v_news_search (
    item_table,
    item_id,
    dt_pub,
    ticker,
    title,
    url,
    source_name,
    body,
    pillar_tags,
    full_text,
    categories,
    tags,
    tickers
) AS
SELECT item_table, item_id, dt_pub, ticker, title, url, source_name, body, pillar_tags, full_text, categories, tags, tickers
FROM v_news_enriched
ORDER BY dt_pub DESC;
