# ChatGPT / Codex connector configuration (opt-in only)
# Add the `codex-review` label to a pull request when you want an AI review.
version: 1
review:
  auto: false
  triggers:
    labels:
      - codex-review
  ignore:
    paths:
      - "archive/**"
      - "datasets/**"
      - "website_django/venv/**"
      - "website_django/static/**"
      - "website_django/staticfiles/**"
      - "tests/fixtures/**"
      - "docs/**"
      - "infra/**"
