DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'PROC_GEMINI_JOBS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE PROC_GEMINI_JOBS (
                JOB_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ROUTINE_CODE VARCHAR2(50),
                ROUTINE_LABEL VARCHAR2(200),
                CONTENT_TEXT CLOB,
                INSTRUCTIONS CLOB NOT NULL,
                FILE_NAME VARCHAR2(512),
                FILE_MIME VARCHAR2(128),
                FILE_BLOB BLOB,
                STATUS VARCHAR2(30),
                CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
                UPDATED_AT TIMESTAMP,
                RESULT_TEXT CLOB,
                ERROR_TEXT CLOB
            )
        ';
    END IF;

    SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'PROC_GEMINI_APPROVALS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE PROC_GEMINI_APPROVALS (
                APPROVAL_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                SOURCE_JOB_ID NUMBER,
                REQUEST_TYPE VARCHAR2(50),
                TITLE VARCHAR2(512),
                PROPOSED_TEXT CLOB,
                DETAILS CLOB,
                GEMINI_COMMENTS CLOB,
                FILE_NAME VARCHAR2(512),
                FILE_MIME VARCHAR2(128),
                FILE_BLOB BLOB,
                STATUS VARCHAR2(30),
                CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
                DECIDED_AT TIMESTAMP,
                DECIDED_BY VARCHAR2(256),
                DECISION_NOTES CLOB
            )
        ';
    END IF;

    SELECT COUNT(1)
    INTO v_count
    FROM user_tab_columns
    WHERE table_name = 'PROC_GEMINI_APPROVALS' AND column_name = 'GEMINI_COMMENTS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PROC_GEMINI_APPROVALS ADD (GEMINI_COMMENTS CLOB)';
    END IF;
END;
/
