target-version = "py311"
extend-exclude = [
    ".ask_facade",
    ".gemini_cli_router",
    "app.py",
    "ask2_cors_mw.py",
    "ask2_llm_orchestrator.py",
    "ask2_llm_refiner.py",
    "composer",
    "db_helper.py",
    "failover_mw.py",
    "gemini_adapter.py",
    "ingest_snippets.py",
    "nosuggest_mw.py",
    "orchestrator_mw.py",
    "refinedriver.py",
    "retrieval",
    "route_direct.py",
    "route_simple.py",
    "sitecustomize.py",
    "smalltalk_wsgi.py",
    "tests/test_health_and_contract.py",
    "tools",
    "wsgi_refine_wrapper.py",
]
