-- SC_IDX TECH100 portfolio analytics schema v1 drop helpers (idempotent)

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW SC_IDX_PORTFOLIO_SECTOR_DAILY_V';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_MODEL_PORTFOLIO_CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_PORTFOLIO_OPT_INPUTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_PORTFOLIO_POSITION_DAILY';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_PORTFOLIO_ANALYTICS_DAILY';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
