-- Auditable corporate-action state for the TECH100 adjusted-price methodology.
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SC_IDX_CORPORATE_ACTIONS (
      INDEX_CODE VARCHAR2(32) NOT NULL,
      TICKER VARCHAR2(32) NOT NULL,
      ACTION_TYPE VARCHAR2(32) NOT NULL,
      EFFECTIVE_DATE DATE NOT NULL,
      RATIO NUMBER(20,10) NOT NULL,
      CONFIRMATION_STATUS VARCHAR2(16) DEFAULT 'PENDING' NOT NULL,
      SOURCE_TYPE VARCHAR2(32),
      SOURCE_REFERENCE VARCHAR2(1000),
      DETECTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONFIRMED_AT TIMESTAMP,
      PROCESSING_METHOD VARCHAR2(64) DEFAULT 'REFRESH_ADJUSTED_HISTORY' NOT NULL,
      APPLIED_AT TIMESTAMP,
      AFFECTED_START_DATE DATE,
      PROCESSING_RUN_ID VARCHAR2(128),
      CONSTRAINT SC_IDX_CA_PK PRIMARY KEY (INDEX_CODE,TICKER,ACTION_TYPE,EFFECTIVE_DATE),
      CONSTRAINT SC_IDX_CA_STATUS_CK CHECK (CONFIRMATION_STATUS IN ('PENDING','CONFIRMED','REJECTED','APPLIED')),
      CONSTRAINT SC_IDX_CA_RATIO_CK CHECK (RATIO > 0)
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SC_IDX_CA_BACKUP_MANIFEST (
      RUN_ID VARCHAR2(128) NOT NULL,
      BACKUP_TAG VARCHAR2(32) NOT NULL,
      TARGET_OBJECT VARCHAR2(128) NOT NULL,
      BACKUP_OBJECT VARCHAR2(128) NOT NULL,
      START_DATE DATE NOT NULL,
      END_DATE DATE NOT NULL,
      SOURCE_ROW_COUNT NUMBER NOT NULL,
      BACKUP_ROW_COUNT NUMBER NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      VALIDATION_STATUS VARCHAR2(16) NOT NULL,
      CONSTRAINT SC_IDX_CA_BM_PK PRIMARY KEY (RUN_ID,TARGET_OBJECT),
      CONSTRAINT SC_IDX_CA_BM_TAG_UK UNIQUE (BACKUP_TAG,TARGET_OBJECT),
      CONSTRAINT SC_IDX_CA_BM_STATUS_CK CHECK (VALIDATION_STATUS IN ('VALIDATED','INVALID'))
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX SC_IDX_CA_STATUS_IX ON SC_IDX_CORPORATE_ACTIONS (CONFIRMATION_STATUS,EFFECTIVE_DATE)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
