-- Drop SC_IDX index engine schema v1 objects (idempotent)

-- SC_IDX_LEVELS
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_LEVELS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- SC_IDX_DIVISOR
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_DIVISOR';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- SC_IDX_HOLDINGS
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_HOLDINGS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- SC_IDX_PRICES_CANON
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_PRICES_CANON';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- SC_IDX_PRICES_RAW
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_PRICES_RAW';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
