-- Drop SC_IDX index calc v1 tables (idempotent)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_STATS_DAILY';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_CONTRIBUTION_DAILY';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_CONSTITUENT_DAILY';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
