-- SC_IDX_ALERT_STATE v1 (idempotent create)
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE SC_IDX_ALERT_STATE (
      ALERT_NAME VARCHAR2(64) PRIMARY KEY,
      LAST_SENT_UTC_DATE DATE,
      LAST_SENT_AT TIMESTAMP,
      LAST_STATUS VARCHAR2(16),
      LAST_DETAIL_HASH VARCHAR2(64)
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/
