-- Drop SC_IDX_TRADING_DAYS + SC_IDX_IMPUTATIONS v1 (idempotent)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_IMPUTATIONS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SC_IDX_TRADING_DAYS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
