-- SC_IDX_JOB_RUNS v1 (idempotent create)
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE SC_IDX_JOB_RUNS (
      RUN_ID VARCHAR2(36) PRIMARY KEY,
      JOB_NAME VARCHAR2(64) NOT NULL,
      STARTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      ENDED_AT TIMESTAMP,
      START_DATE DATE,
      END_DATE DATE,
      PROVIDER VARCHAR2(32),
      ORACLE_USER VARCHAR2(64),
      USAGE_CURRENT NUMBER,
      USAGE_LIMIT NUMBER,
      USAGE_REMAINING NUMBER,
      CREDIT_BUFFER NUMBER,
      MAX_PROVIDER_CALLS NUMBER,
      PROVIDER_CALLS_USED NUMBER,
      RAW_UPSERTS NUMBER,
      CANON_UPSERTS NUMBER,
      RAW_OK NUMBER,
      RAW_ERROR NUMBER,
      RAW_MISSING NUMBER,
      STATUS VARCHAR2(16),
      ERROR_MSG VARCHAR2(4000)
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/
