-- SC_IDX TECH100 portfolio analytics schema v1 (idempotent)

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SC_IDX_PORTFOLIO_ANALYTICS_DAILY (
      MODEL_CODE VARCHAR2(32) NOT NULL,
      TRADE_DATE DATE NOT NULL,
      MODEL_NAME VARCHAR2(128) NOT NULL,
      REBALANCE_DATE DATE,
      LEVEL_TR NUMBER(18,6) NOT NULL,
      RET_1D NUMBER,
      RET_5D NUMBER,
      RET_20D NUMBER,
      RET_MTD NUMBER,
      RET_YTD NUMBER,
      VOL_20D NUMBER,
      VOL_60D NUMBER,
      DRAWDOWN_TO_DATE NUMBER,
      MAX_DRAWDOWN_252D NUMBER,
      N_CONSTITUENTS NUMBER,
      N_IMPUTED NUMBER,
      TOP1_WEIGHT NUMBER,
      TOP5_WEIGHT NUMBER,
      HERFINDAHL NUMBER,
      AVG_GOVERNANCE_SCORE NUMBER,
      AVG_MOMENTUM_20D NUMBER,
      AVG_LOW_VOL_60D NUMBER,
      SECTOR_COUNT NUMBER,
      FACTOR_GOVERNANCE_EXPOSURE NUMBER,
      FACTOR_MOMENTUM_EXPOSURE NUMBER,
      FACTOR_LOW_VOL_EXPOSURE NUMBER,
      FACTOR_SECTOR_TILT_ABS NUMBER,
      FACTOR_CONCENTRATION NUMBER,
      COMPUTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT SC_IDX_PORTFOLIO_ANALYTICS_PK PRIMARY KEY (MODEL_CODE, TRADE_DATE)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SC_IDX_PORTFOLIO_POSITION_DAILY (
      MODEL_CODE VARCHAR2(32) NOT NULL,
      TRADE_DATE DATE NOT NULL,
      TICKER VARCHAR2(32) NOT NULL,
      MODEL_NAME VARCHAR2(128) NOT NULL,
      REBALANCE_DATE DATE,
      PORT_DATE DATE,
      COMPANY_NAME VARCHAR2(200),
      SECTOR VARCHAR2(128),
      MODEL_WEIGHT NUMBER,
      BENCHMARK_WEIGHT NUMBER,
      ACTIVE_WEIGHT NUMBER,
      PRICE_QUALITY VARCHAR2(16),
      RET_1D NUMBER,
      CONTRIB_1D NUMBER,
      CONTRIB_5D NUMBER,
      CONTRIB_20D NUMBER,
      CONTRIB_MTD NUMBER,
      CONTRIB_YTD NUMBER,
      GOVERNANCE_SCORE NUMBER,
      TRANSPARENCY NUMBER,
      ETHICAL_PRINCIPLES NUMBER,
      GOVERNANCE_STRUCTURE NUMBER,
      REGULATORY_ALIGNMENT NUMBER,
      STAKEHOLDER_ENGAGEMENT NUMBER,
      MOMENTUM_20D NUMBER,
      LOW_VOL_60D NUMBER,
      COMPUTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT SC_IDX_PORTFOLIO_POSITION_PK PRIMARY KEY (MODEL_CODE, TRADE_DATE, TICKER)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SC_IDX_PORTFOLIO_OPT_INPUTS (
      TRADE_DATE DATE NOT NULL,
      PORT_DATE DATE,
      TICKER VARCHAR2(32) NOT NULL,
      COMPANY_NAME VARCHAR2(200),
      SECTOR VARCHAR2(128),
      BENCHMARK_WEIGHT NUMBER,
      GOVERNANCE_SCORE NUMBER,
      MOMENTUM_20D NUMBER,
      LOW_VOL_60D NUMBER,
      GOVERNANCE_RANK NUMBER,
      MOMENTUM_RANK NUMBER,
      LOW_VOL_RANK NUMBER,
      HYBRID_RANK NUMBER,
      PRICE_QUALITY VARCHAR2(16),
      ELIGIBLE_FLAG CHAR(1),
      COMPUTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT SC_IDX_PORTFOLIO_OPT_INPUTS_PK PRIMARY KEY (TRADE_DATE, TICKER)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SC_IDX_MODEL_PORTFOLIO_CONSTRAINTS (
      MODEL_CODE VARCHAR2(32) NOT NULL,
      CONSTRAINT_KEY VARCHAR2(64) NOT NULL,
      CONSTRAINT_TYPE VARCHAR2(16) NOT NULL,
      CONSTRAINT_VALUE VARCHAR2(400),
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT SC_IDX_MODEL_PORTFOLIO_CONSTRAINTS_PK PRIMARY KEY (MODEL_CODE, CONSTRAINT_KEY)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_SC_IDX_PORTFOLIO_AN_DT ON SC_IDX_PORTFOLIO_ANALYTICS_DAILY(TRADE_DATE)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_SC_IDX_PORTFOLIO_POS_DT_MODEL ON SC_IDX_PORTFOLIO_POSITION_DAILY(TRADE_DATE, MODEL_CODE)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_SC_IDX_PORTFOLIO_POS_MODEL_TKR_DT ON SC_IDX_PORTFOLIO_POSITION_DAILY(MODEL_CODE, TICKER, TRADE_DATE)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_SC_IDX_PORTFOLIO_OPT_DT ON SC_IDX_PORTFOLIO_OPT_INPUTS(TRADE_DATE)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE VIEW SC_IDX_PORTFOLIO_SECTOR_DAILY_V AS
SELECT
  MODEL_CODE,
  TRADE_DATE,
  NVL(SECTOR, 'Unclassified') AS SECTOR,
  SUM(MODEL_WEIGHT) AS SECTOR_WEIGHT,
  SUM(BENCHMARK_WEIGHT) AS BENCHMARK_SECTOR_WEIGHT,
  SUM(ACTIVE_WEIGHT) AS ACTIVE_SECTOR_WEIGHT,
  SUM(CONTRIB_1D) AS CONTRIB_1D,
  SUM(CONTRIB_5D) AS CONTRIB_5D,
  SUM(CONTRIB_20D) AS CONTRIB_20D,
  SUM(CONTRIB_MTD) AS CONTRIB_MTD,
  SUM(CONTRIB_YTD) AS CONTRIB_YTD
FROM SC_IDX_PORTFOLIO_POSITION_DAILY
GROUP BY MODEL_CODE, TRADE_DATE, NVL(SECTOR, 'Unclassified')
/
