-- SC_IDX_TRADING_DAYS + SC_IDX_IMPUTATIONS v1 (idempotent create)
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE SC_IDX_TRADING_DAYS (
      TRADE_DATE DATE PRIMARY KEY,
      SOURCE VARCHAR2(32) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE SC_IDX_IMPUTATIONS (
      INDEX_CODE VARCHAR2(32) NOT NULL,
      TRADE_DATE DATE NOT NULL,
      TICKER VARCHAR2(32) NOT NULL,
      IMPUTED_FROM_DATE DATE,
      IMPUTED_PRICE NUMBER(18,6),
      REASON VARCHAR2(128) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT SC_IDX_IMPUTATIONS_PK PRIMARY KEY (INDEX_CODE, TRADE_DATE, TICKER)
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/
