-- SC_IDX_PIPELINE_STATE v1 (idempotent create)
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE SC_IDX_PIPELINE_STATE (
      RUN_ID VARCHAR2(36) NOT NULL,
      PIPELINE_NAME VARCHAR2(64) NOT NULL,
      STAGE_NAME VARCHAR2(64) NOT NULL,
      STAGE_STATUS VARCHAR2(16) NOT NULL,
      STARTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      ENDED_AT TIMESTAMP,
      DETAILS VARCHAR2(4000),
      CONSTRAINT SC_IDX_PIPELINE_STATE_PK PRIMARY KEY (RUN_ID, STAGE_NAME)
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/
