-- SC_IDX index engine schema v1 (idempotent)

-- SC_IDX_PRICES_RAW
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SC_IDX_PRICES_RAW (
      TICKER VARCHAR2(32) NOT NULL,
      TRADE_DATE DATE NOT NULL,
      PROVIDER VARCHAR2(32) NOT NULL,
      CLOSE_PX NUMBER(18,6),
      ADJ_CLOSE_PX NUMBER(18,6),
      VOLUME NUMBER(18,0),
      CURRENCY VARCHAR2(8),
      INGESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      STATUS VARCHAR2(32) NOT NULL,
      ERROR_MSG VARCHAR2(4000),
      CONSTRAINT PK_SC_IDX_PRICES_RAW PRIMARY KEY (TICKER, TRADE_DATE, PROVIDER)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- SC_IDX_PRICES_CANON
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SC_IDX_PRICES_CANON (
      TICKER VARCHAR2(32) NOT NULL,
      TRADE_DATE DATE NOT NULL,
      CANON_CLOSE_PX NUMBER(18,6),
      CANON_ADJ_CLOSE_PX NUMBER(18,6),
      CHOSEN_PROVIDER VARCHAR2(32) NOT NULL,
      PROVIDERS_OK NUMBER(3) NOT NULL,
      DIVERGENCE_PCT NUMBER(9,6),
      QUALITY VARCHAR2(16) NOT NULL,
      COMPUTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_SC_IDX_PRICES_CANON PRIMARY KEY (TICKER, TRADE_DATE)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- SC_IDX_HOLDINGS
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SC_IDX_HOLDINGS (
      INDEX_CODE VARCHAR2(32) NOT NULL,
      REBALANCE_DATE DATE NOT NULL,
      TICKER VARCHAR2(32) NOT NULL,
      TARGET_WEIGHT NUMBER(12,8) NOT NULL,
      SHARES NUMBER(24,12) NOT NULL,
      CONSTRAINT PK_SC_IDX_HOLDINGS PRIMARY KEY (INDEX_CODE, REBALANCE_DATE, TICKER)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- SC_IDX_DIVISOR
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SC_IDX_DIVISOR (
      INDEX_CODE VARCHAR2(32) NOT NULL,
      EFFECTIVE_DATE DATE NOT NULL,
      DIVISOR NUMBER(24,12) NOT NULL,
      REASON VARCHAR2(256),
      CONSTRAINT PK_SC_IDX_DIVISOR PRIMARY KEY (INDEX_CODE, EFFECTIVE_DATE)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- SC_IDX_LEVELS
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SC_IDX_LEVELS (
      INDEX_CODE VARCHAR2(32) NOT NULL,
      TRADE_DATE DATE NOT NULL,
      LEVEL_TR NUMBER(18,6) NOT NULL,
      COMPUTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_SC_IDX_LEVELS PRIMARY KEY (INDEX_CODE, TRADE_DATE)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- Indexes
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_SC_IDX_PRICES_RAW_DT ON SC_IDX_PRICES_RAW(TRADE_DATE)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_SC_IDX_PRICES_CANON_DT ON SC_IDX_PRICES_CANON(TRADE_DATE)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_SC_IDX_LEVELS_DT ON SC_IDX_LEVELS(TRADE_DATE)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
