DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'SC_SITE_TERMS_ACCEPTANCE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE SC_SITE_TERMS_ACCEPTANCE (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                email VARCHAR2(320) NOT NULL,
                terms_version VARCHAR2(20) NOT NULL,
                privacy_version VARCHAR2(20) NOT NULL,
                accepted_at_utc TIMESTAMP DEFAULT SYSTIMESTAMP,
                ip_address VARCHAR2(64),
                user_agent VARCHAR2(512),
                acceptance_context VARCHAR2(64),
                accepted CHAR(1) DEFAULT ''Y'' NOT NULL,
                CONSTRAINT sc_site_terms_acceptance_uk UNIQUE (email, terms_version, privacy_version)
            )
        ';

        EXECUTE IMMEDIATE 'CREATE INDEX sc_site_terms_acceptance_email_idx ON SC_SITE_TERMS_ACCEPTANCE (email)';
    END IF;
END;
/
