DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'U_UX_EVENTS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE U_UX_EVENTS (
                event_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                event_ts TIMESTAMP DEFAULT SYSTIMESTAMP,
                session_id VARCHAR2(64),
                user_email VARCHAR2(320),
                event_type VARCHAR2(64),
                path VARCHAR2(512),
                referrer VARCHAR2(512),
                user_agent VARCHAR2(512),
                ip_hash VARCHAR2(128),
                metadata_json CLOB
            )
        ';

        EXECUTE IMMEDIATE 'CREATE INDEX U_UX_EVENTS_TS_IDX ON U_UX_EVENTS (event_ts)';
        EXECUTE IMMEDIATE 'CREATE INDEX U_UX_EVENTS_TYPE_IDX ON U_UX_EVENTS (event_type)';
        EXECUTE IMMEDIATE 'CREATE INDEX U_UX_EVENTS_USER_IDX ON U_UX_EVENTS (user_email)';
        EXECUTE IMMEDIATE 'CREATE INDEX U_UX_EVENTS_SESSION_IDX ON U_UX_EVENTS (session_id)';
    END IF;
END;
/
