"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def get_env_list(name: str, default: str) -> list[str]:
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable is required")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=False)

DEFAULT_ALLOWED_HOSTS = "sustainacore.org,www.sustainacore.org,preview.sustainacore.org,141.147.76.55,localhost,127.0.0.1"
ALLOWED_HOSTS = get_env_list("DJANGO_ALLOWED_HOSTS", DEFAULT_ALLOWED_HOSTS)

DEFAULT_CSRF_TRUSTED_ORIGINS = (
    "https://sustainacore.org,https://www.sustainacore.org,https://preview.sustainacore.org"
)
CSRF_TRUSTED_ORIGINS = get_env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS", DEFAULT_CSRF_TRUSTED_ORIGINS
)

PREVIEW_HOSTS = get_env_list("PREVIEW_HOSTS", "preview.sustainacore.org")
PREVIEW_MODE = env_bool("PREVIEW_MODE", default=False)
_raw_env = os.environ.get("SUSTAINACORE_ENV")
SUSTAINACORE_ENV = (_raw_env or "development").strip().lower()

SITE_URL = os.environ.get("SITE_URL", "https://sustainacore.org")
DEFAULT_META_DESCRIPTION = (
    "SustainaCore provides open ESG and AI governance data, including TECH100 index insights, "
    "curated news, and evidence-backed indicators for responsible technology teams."
)
STATIC_VERSION = os.environ.get("STATIC_VERSION", "dev")
SITEMAP_CACHE_SECONDS = int(os.environ.get("SITEMAP_CACHE_SECONDS", "3600"))
TELEMETRY_POLICY_VERSION = os.environ.get("TELEMETRY_POLICY_VERSION", "2025-12-30")
TELEMETRY_HASH_SALT = os.environ.get("TELEMETRY_HASH_SALT", SECRET_KEY)
TELEMETRY_RETENTION_DAYS = int(os.environ.get("TELEMETRY_RETENTION_DAYS", "180"))
TELEMETRY_CONSENT_MAX_AGE_DAYS = int(os.environ.get("TELEMETRY_CONSENT_MAX_AGE_DAYS", "180"))
TELEMETRY_TRUST_X_FORWARDED_FOR = env_bool("TELEMETRY_TRUST_X_FORWARDED_FOR", default=False)
TELEMETRY_STORE_ASK2_TEXT = env_bool("TELEMETRY_STORE_ASK2_TEXT", default=False)
ASK2_STORE_CONVERSATIONS = env_bool("ASK2_STORE_CONVERSATIONS", default=False)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'ask2',
    'telemetry',
    'sc_admin_portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.analytics_middleware.AnonCookieMiddleware',
    'core.auth_middleware.AuthCookieMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'core.analytics_middleware.PageViewAnalyticsMiddleware',
    'telemetry.middleware.TelemetryMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.seo_defaults',
                'core.context_processors.preview_context',
                'core.context_processors.auth_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

ORACLE_USER = os.environ.get("DB_USER") or os.environ.get("ORACLE_USER")
ORACLE_PASSWORD = (
    os.environ.get("DB_PASSWORD")
    or os.environ.get("DB_PASS")
    or os.environ.get("ORACLE_PASSWORD")
)
ORACLE_DSN = (
    os.environ.get("DB_DSN")
    or os.environ.get("ORACLE_DSN")
    or os.environ.get("ORACLE_CONNECT_STRING")
)
ORACLE_CONFIGURED = bool(ORACLE_USER and ORACLE_PASSWORD and ORACLE_DSN)
if ORACLE_CONFIGURED:
    try:
        import oracledb  # type: ignore
        import sys

        lib_dir = os.getenv("ORACLE_CLIENT_LIB_DIR", "/opt/oracle/instantclient_23")
        config_dir = os.getenv("TNS_ADMIN", "/opt/adb_wallet_tp")
        try:
            oracledb.init_oracle_client(lib_dir=lib_dir, config_dir=config_dir)
        except Exception:
            pass

        sys.modules.setdefault("cx_Oracle", oracledb)
    except Exception:
        pass

PRODUCTION_MODE = SUSTAINACORE_ENV in {"production", "preview"} and not DEBUG
if PRODUCTION_MODE and not ORACLE_CONFIGURED:
    raise ImproperlyConfigured(
        "Oracle is required in production. Set DB_USER/DB_PASSWORD/DB_DSN "
        "(or ORACLE_USER/ORACLE_PASSWORD/ORACLE_DSN/ORACLE_CONNECT_STRING)."
    )

if ORACLE_CONFIGURED:
    oracle_db = {
        "ENGINE": "django.db.backends.oracle",
        "NAME": ORACLE_DSN,
        "USER": ORACLE_USER,
        "PASSWORD": ORACLE_PASSWORD,
    }
    if PRODUCTION_MODE:
        DATABASES["default"] = oracle_db
    else:
        DATABASES["oracle"] = oracle_db

if DATABASES["default"]["ENGINE"] == "django.db.backends.oracle":
    TELEMETRY_DB_ALIAS = "default"
elif "oracle" in DATABASES:
    TELEMETRY_DB_ALIAS = "oracle"
else:
    TELEMETRY_DB_ALIAS = "default"
DATABASE_ROUTERS = ["telemetry.db_router.TelemetryRouter"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [BASE_DIR / "static"]

# Cache (used by TECH100 Oracle queries)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "sustainacore-cache",
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Backend API configuration (VM1)
BACKEND_API_BASE = os.environ.get("BACKEND_API_BASE", "http://10.0.0.120:8080")
BACKEND_API_TOKEN = os.environ.get("BACKEND_API_TOKEN", "")

SUSTAINACORE_BACKEND_URL = os.environ.get("SUSTAINACORE_BACKEND_URL", "http://127.0.0.1:8091")
SUSTAINACORE_BACKEND_TIMEOUT = float(os.environ.get("SUSTAINACORE_BACKEND_TIMEOUT", "5"))

TERMS_VERSION = os.environ.get("SUSTAINACORE_TERMS_VERSION", "2025-12-28")
PRIVACY_VERSION = os.environ.get("SUSTAINACORE_PRIVACY_VERSION", "2025-12-28")
