from __future__ import annotations

from typing import Optional

import oracledb
from django.conf import settings
from django.utils.timezone import now

from core.oracle_db import get_connection


TABLE_NAME = "SC_SITE_TERMS_ACCEPTANCE"


def _ensure_terms_table(cursor: oracledb.Cursor) -> None:
    try:
        cursor.execute(
            f"""
            CREATE TABLE {TABLE_NAME} (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                email VARCHAR2(320) NOT NULL,
                terms_version VARCHAR2(20) NOT NULL,
                privacy_version VARCHAR2(20) NOT NULL,
                accepted_at_utc TIMESTAMP DEFAULT SYSTIMESTAMP,
                ip_address VARCHAR2(64),
                user_agent VARCHAR2(512),
                acceptance_context VARCHAR2(64),
                accepted CHAR(1) DEFAULT 'Y' NOT NULL,
                CONSTRAINT sc_site_terms_acceptance_uk UNIQUE (email, terms_version, privacy_version)
            )
            """
        )
        cursor.execute(
            f"CREATE INDEX sc_site_terms_acceptance_email_idx ON {TABLE_NAME} (email)"
        )
    except oracledb.DatabaseError as exc:
        error = exc.args[0] if exc.args else None
        if getattr(error, "code", None) == 955:
            return
        raise


def _client_ip(request) -> str:
    forwarded = request.META.get("HTTP_X_FORWARDED_FOR")
    if forwarded:
        return forwarded.split(",")[0].strip()
    return request.META.get("REMOTE_ADDR", "") or ""


def record_terms_acceptance(email: str, request, context: str) -> bool:
    if not email:
        return False
    terms_version = settings.TERMS_VERSION
    privacy_version = settings.PRIVACY_VERSION
    ip_address = _client_ip(request) or None
    user_agent = request.META.get("HTTP_USER_AGENT", "") or None
    accepted_at = now()
    try:
        with get_connection() as conn:
            with conn.cursor() as cursor:
                _ensure_terms_table(cursor)
                try:
                    cursor.execute(
                        f"""
                        INSERT INTO {TABLE_NAME} (
                            email,
                            terms_version,
                            privacy_version,
                            accepted_at_utc,
                            ip_address,
                            user_agent,
                            acceptance_context,
                            accepted
                        )
                        VALUES (
                            :email,
                            :terms_version,
                            :privacy_version,
                            :accepted_at_utc,
                            :ip_address,
                            :user_agent,
                            :acceptance_context,
                            'Y'
                        )
                        """,
                        {
                            "email": email,
                            "terms_version": terms_version,
                            "privacy_version": privacy_version,
                            "accepted_at_utc": accepted_at,
                            "ip_address": ip_address[:64] if ip_address else None,
                            "user_agent": user_agent[:512] if user_agent else None,
                            "acceptance_context": (context or "")[:64] if context else None,
                        },
                    )
                    conn.commit()
                except oracledb.DatabaseError as exc:
                    error = exc.args[0] if exc.args else None
                    if getattr(error, "code", None) == 1:
                        return True
                    raise
        return True
    except Exception:
        return False


def has_terms_acceptance(email: str) -> bool:
    if not email:
        return False
    terms_version = settings.TERMS_VERSION
    privacy_version = settings.PRIVACY_VERSION
    try:
        with get_connection() as conn:
            with conn.cursor() as cursor:
                _ensure_terms_table(cursor)
                cursor.execute(
                    f"""
                    SELECT 1
                    FROM {TABLE_NAME}
                    WHERE email = :email
                      AND terms_version = :terms_version
                      AND privacy_version = :privacy_version
                      AND accepted = 'Y'
                      AND ROWNUM = 1
                    """,
                    {
                        "email": email,
                        "terms_version": terms_version,
                        "privacy_version": privacy_version,
                    },
                )
                return cursor.fetchone() is not None
    except Exception:
        return False
