"""Initialize PROC_RESEARCH_REQUESTS table."""
from __future__ import annotations

import logging
import os
import sys

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
if ROOT_DIR not in sys.path:
    sys.path.append(ROOT_DIR)

import db_helper  # noqa: E402
from tools.oracle.env_bootstrap import load_env_files  # noqa: E402

LOGGER = logging.getLogger("research_generator.init_proc_research_requests")


def main() -> int:
    load_env_files()
    conn = db_helper.get_connection()
    cur = conn.cursor()
    try:
        cur.execute(
            """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE proc_research_requests (
                        request_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR2(40) NOT NULL,
                        request_type VARCHAR2(40) NOT NULL,
                        company_ticker VARCHAR2(40),
                        window_start TIMESTAMP,
                        window_end TIMESTAMP,
                        editor_notes CLOB,
                        source_approval_id NUMBER,
                        created_by VARCHAR2(80),
                        created_at TIMESTAMP,
                        updated_at TIMESTAMP,
                        result_text CLOB
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
            """
        )
        conn.commit()
    finally:
        conn.close()
    LOGGER.info("PROC_RESEARCH_REQUESTS ready")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
