"""Initialize PROC_REPORT_INSIGHTS table."""
from __future__ import annotations

import logging
import os
import sys

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
if ROOT_DIR not in sys.path:
    sys.path.append(ROOT_DIR)

import db_helper  # noqa: E402
from tools.oracle.env_bootstrap import load_env_files  # noqa: E402

LOGGER = logging.getLogger("research_generator.init_proc_report_insights")


def main() -> int:
    load_env_files()
    conn = db_helper.get_connection()
    cur = conn.cursor()
    try:
        cur.execute(
            """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE proc_report_insights (
                        report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        report_type VARCHAR2(40),
                        generated_at TIMESTAMP,
                        insights_json CLOB
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
            """
        )
        conn.commit()
    finally:
        conn.close()
    LOGGER.info("PROC_REPORT_INSIGHTS ready")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
