"""Initialize PROC_RESEARCH_ALERTS table."""
from __future__ import annotations

import logging
import os
import sys

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
if ROOT_DIR not in sys.path:
    sys.path.append(ROOT_DIR)

import db_helper  # noqa: E402
from tools.oracle.env_bootstrap import load_env_files  # noqa: E402

LOGGER = logging.getLogger("research_generator.init_proc_research_alerts")


def main() -> int:
    load_env_files()
    conn = db_helper.get_connection()
    cur = conn.cursor()
    try:
        cur.execute(
            """
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE proc_research_alerts (
                        alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        created_at TIMESTAMP,
                        request_id NUMBER,
                        approval_id NUMBER,
                        severity VARCHAR2(10),
                        title VARCHAR2(200),
                        details CLOB
                    )
                ';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
            """
        )
        conn.commit()
    finally:
        conn.close()
    LOGGER.info("PROC_RESEARCH_ALERTS ready")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
