BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE proc_research_alerts (
            alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP,
            request_id NUMBER,
            approval_id NUMBER,
            severity VARCHAR2(10),
            title VARCHAR2(200),
            details CLOB
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
