BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE proc_report_insights (
            report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            report_type VARCHAR2(40),
            generated_at TIMESTAMP,
            insights_json CLOB
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
