CREATE TABLE proc_research_requests (
    request_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR2(40) NOT NULL,
    request_type VARCHAR2(40) NOT NULL,
    company_ticker VARCHAR2(40),
    window_start TIMESTAMP,
    window_end TIMESTAMP,
    editor_notes CLOB,
    source_approval_id NUMBER,
    created_by VARCHAR2(80),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    result_text CLOB
);
