# Generated by Django 4.2.27 on 2025-12-30 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebConsent',
            fields=[
                ('consent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('consent_analytics', models.CharField(default='N', max_length=1)),
                ('consent_functional', models.CharField(default='N', max_length=1)),
                ('consent_policy_version', models.CharField(max_length=32)),
                ('source', models.CharField(default='banner', max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('ip_trunc', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'W_WEB_CONSENT',
            },
        ),
        migrations.CreateModel(
            name='WebEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_ts', models.DateTimeField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
                ('consent_analytics_effective', models.CharField(default='N', max_length=1)),
                ('event_type', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=512)),
                ('query_string', models.TextField(blank=True, null=True)),
                ('http_method', models.CharField(blank=True, max_length=16, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, max_length=512, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('ip_trunc', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('country_code', models.CharField(blank=True, max_length=8, null=True)),
                ('region_code', models.CharField(blank=True, max_length=16, null=True)),
                ('payload_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'W_WEB_EVENT',
            },
        ),
        migrations.CreateModel(
            name='WebSession',
            fields=[
                ('session_row_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('first_seen_ts', models.DateTimeField()),
                ('last_seen_ts', models.DateTimeField()),
                ('country_code', models.CharField(blank=True, max_length=8, null=True)),
                ('region_code', models.CharField(blank=True, max_length=16, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'W_WEB_SESSION',
            },
        ),
    ]
