# Generated by Django 4.2.27 on 2025-12-30 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAsk2Conversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('last_message_at', models.DateTimeField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
                ('anon_id', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('ip_prefix', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('path_first', models.CharField(blank=True, max_length=512, null=True)),
                ('consent_analytics_effective', models.CharField(blank=True, max_length=1, null=True)),
                ('metadata_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'W_WEB_ASK2_CONVERSATION',
            },
        ),
        migrations.CreateModel(
            name='WebAsk2Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('content_len', models.IntegerField()),
                ('model_name', models.CharField(blank=True, max_length=128, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('tokens_in', models.IntegerField(blank=True, null=True)),
                ('tokens_out', models.IntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('error_class', models.CharField(blank=True, max_length=128, null=True)),
                ('error_msg', models.CharField(blank=True, max_length=512, null=True)),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telemetry.webask2conversation')),
            ],
            options={
                'db_table': 'W_WEB_ASK2_MESSAGE',
            },
        ),
    ]
