# Generated by Codex on 2026-03-06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0002_webask2conversation_webask2message"),
    ]

    operations = [
        migrations.AddField(
            model_name="webevent",
            name="debug_json",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="webevent",
            name="event_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="webevent",
            name="is_bot",
            field=models.CharField(default="N", max_length=1),
        ),
        migrations.AddField(
            model_name="webevent",
            name="referrer_host",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="WebEventDaily",
            fields=[
                ("aggregate_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("bucket_date", models.DateField()),
                ("event_type", models.CharField(max_length=64)),
                ("event_name", models.CharField(blank=True, max_length=64, null=True)),
                ("path", models.CharField(max_length=512)),
                ("path_hash", models.CharField(max_length=64)),
                ("referrer_host", models.CharField(blank=True, max_length=255, null=True)),
                ("country_code", models.CharField(blank=True, max_length=8, null=True)),
                ("consent_analytics_effective", models.CharField(default="N", max_length=1)),
                ("is_bot", models.CharField(default="N", max_length=1)),
                ("status_class", models.CharField(blank=True, max_length=8, null=True)),
                ("event_count", models.IntegerField(default=0)),
                ("unique_sessions", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("total_response_ms", models.IntegerField(default=0)),
                ("max_response_ms", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "W_WEB_EVENT_DAILY",
            },
        ),
        migrations.AddIndex(
            model_name="webeventdaily",
            index=models.Index(fields=["bucket_date", "event_type"], name="W_WEB_EVENT_bucket__f8d81c_idx"),
        ),
        migrations.AddIndex(
            model_name="webeventdaily",
            index=models.Index(fields=["bucket_date", "path_hash"], name="W_WEB_EVENT_bucket__4538b0_idx"),
        ),
    ]
