-- Row counts
SELECT 'DIM_LOAD_BATCH' AS table_name, COUNT(*) AS row_count FROM DIM_LOAD_BATCH;
SELECT 'STG_AI_REG_RECORD_RAW' AS table_name, COUNT(*) AS row_count FROM STG_AI_REG_RECORD_RAW;
SELECT 'DIM_JURISDICTION' AS table_name, COUNT(*) AS row_count FROM DIM_JURISDICTION;
SELECT 'DIM_INSTRUMENT' AS table_name, COUNT(*) AS row_count FROM DIM_INSTRUMENT;
SELECT 'FACT_INSTRUMENT_SNAPSHOT' AS table_name, COUNT(*) AS row_count FROM FACT_INSTRUMENT_SNAPSHOT;
SELECT 'DIM_TAG' AS table_name, COUNT(*) AS row_count FROM DIM_TAG;
SELECT 'BRG_SNAPSHOT_TAG' AS table_name, COUNT(*) AS row_count FROM BRG_SNAPSHOT_TAG;
SELECT 'DIM_SECTOR' AS table_name, COUNT(*) AS row_count FROM DIM_SECTOR;
SELECT 'BRG_SNAPSHOT_SECTOR' AS table_name, COUNT(*) AS row_count FROM BRG_SNAPSHOT_SECTOR;
SELECT 'DIM_AUTHORITY' AS table_name, COUNT(*) AS row_count FROM DIM_AUTHORITY;
SELECT 'BRG_SNAPSHOT_AUTHORITY' AS table_name, COUNT(*) AS row_count FROM BRG_SNAPSHOT_AUTHORITY;
SELECT 'FACT_SNAPSHOT_OBLIGATION' AS table_name, COUNT(*) AS row_count FROM FACT_SNAPSHOT_OBLIGATION;
SELECT 'DIM_SOURCE' AS table_name, COUNT(*) AS row_count FROM DIM_SOURCE;
SELECT 'BRG_SNAPSHOT_SOURCE' AS table_name, COUNT(*) AS row_count FROM BRG_SNAPSHOT_SOURCE;
SELECT 'FACT_SNAPSHOT_MILESTONE_DATE' AS table_name, COUNT(*) AS row_count FROM FACT_SNAPSHOT_MILESTONE_DATE;
SELECT 'BRG_SNAPSHOT_BATCH' AS table_name, COUNT(*) AS row_count FROM BRG_SNAPSHOT_BATCH;

-- As-of coverage
SELECT 'AS_OF_RANGE' AS metric, MIN(AS_OF_DATE) AS min_as_of, MAX(AS_OF_DATE) AS max_as_of
FROM FACT_INSTRUMENT_SNAPSHOT;

-- Join sanity checks (expect 0)
SELECT COUNT(*) AS orphan_snapshot_jur
FROM FACT_INSTRUMENT_SNAPSHOT s
LEFT JOIN DIM_JURISDICTION j ON s.JURISDICTION_SK = j.JURISDICTION_SK
WHERE j.JURISDICTION_SK IS NULL;

SELECT COUNT(*) AS orphan_snapshot_inst
FROM FACT_INSTRUMENT_SNAPSHOT s
LEFT JOIN DIM_INSTRUMENT i ON s.INSTRUMENT_SK = i.INSTRUMENT_SK
WHERE i.INSTRUMENT_SK IS NULL;

SELECT COUNT(*) AS orphan_source_bridge
FROM BRG_SNAPSHOT_SOURCE b
LEFT JOIN DIM_SOURCE s ON b.SOURCE_SK = s.SOURCE_SK
WHERE s.SOURCE_SK IS NULL;

SELECT COUNT(*) AS orphan_tag_bridge
FROM BRG_SNAPSHOT_TAG b
LEFT JOIN DIM_TAG t ON b.TAG_SK = t.TAG_SK
WHERE t.TAG_SK IS NULL;

SELECT COUNT(*) AS orphan_sector_bridge
FROM BRG_SNAPSHOT_SECTOR b
LEFT JOIN DIM_SECTOR s ON b.SECTOR_SK = s.SECTOR_SK
WHERE s.SECTOR_SK IS NULL;

SELECT COUNT(*) AS orphan_authority_bridge
FROM BRG_SNAPSHOT_AUTHORITY b
LEFT JOIN DIM_AUTHORITY a ON b.AUTHORITY_SK = a.AUTHORITY_SK
WHERE a.AUTHORITY_SK IS NULL;

-- Snapshots without sources (informational)
SELECT COUNT(*) AS snapshots_without_source
FROM FACT_INSTRUMENT_SNAPSHOT s
LEFT JOIN BRG_SNAPSHOT_SOURCE b ON s.SNAPSHOT_SK = b.SNAPSHOT_SK
WHERE b.SNAPSHOT_SK IS NULL;
