name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VM_HOST: ${{ secrets.VM_HOST }}
      VM_USER: ${{ secrets.VM_USER }}
      VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          printf '%s\n' "$VM_SSH_KEY" > ~/.ssh/id_vm
          chmod 600 ~/.ssh/id_vm
          ssh-keyscan -H "$VM_HOST" >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/id_vm -o StrictHostKeyChecking=yes "${VM_USER}@${VM_HOST}" 'bash -s' <<'REMOTE'
          set -euo pipefail
          cd /opt/sustainacore-ai
          git fetch --all
          git reset --hard origin/main
          sudo systemctl daemon-reload || true
          sudo systemctl restart sustainacore-ai.service
          REMOTE

      - name: Verify health
        run: |
          curl --fail --retry 12 --retry-delay 5 "http://${VM_HOST}:8080/healthz"

      - name: Service logs (on failure)
        if: failure()
        run: |
          ssh -i ~/.ssh/id_vm -o StrictHostKeyChecking=yes "${VM_USER}@${VM_HOST}" \
            'journalctl -u sustainacore-ai.service -n 200 --no-pager' | tee deploy_logs.txt

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deploy-logs
          path: deploy_logs.txt
          if-no-files-found: ignore
