name: Deploy
on: { push: { branches: [main] } }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install -U pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          pip install pytest ruff || true
          ruff check . || true
          pytest -q || true
      - name: Write SSH key
        run: |
          echo "${{ secrets.VM_SSH_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Deploy to VM
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          SSH_KEY: ${{ github.workspace }}/key.pem
        run: bash ops/scripts/deploy_vm.sh
      - name: Verify health endpoint
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
        run: |
          curl --fail --retry 5 --retry-delay 5 "http://${VM_HOST}:8080/healthz"
