name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VM_HOST: ${{ secrets.VM_HOST }}   # ai.sustainacore.org
      VM_USER: ${{ secrets.VM_USER }}   # opc
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Lint & tests
        run: |
          python -m pip install -U pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest ruff
          ruff check .
          pytest -q

      - name: Setup SSH
        env:
          VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}   # PRIVATE key from ~/.ssh/ci_actions
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$VM_SSH_KEY" > ~/.ssh/id_vm
          chmod 600 ~/.ssh/id_vm
          ssh-keyscan -H "$VM_HOST" >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/id_vm -o StrictHostKeyChecking=yes ${VM_USER}@${VM_HOST} 'bash -s' <<'REMOTE'
          set -euo pipefail
          cd /opt/sustainacore-ai
          git fetch --all
          git reset --hard origin/main
          sudo systemctl daemon-reload || true
          sudo systemctl restart sustainacore-ai.service
          REMOTE

      - name: Verify health endpoint
        run: |
          curl --fail --retry 20 --retry-delay 5 "http://${VM_HOST}:8080/healthz"
